#!/usr/bin/env python

'''
3a. Retrieve a list of all the devices in NetBox.
'''
import requests
from pprint import pprint

import os

from urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)

# Set the token based on the NETBOX_TOKEN environment variable
token = os.environ["NETBOX_TOKEN"]
url = "https://netbox.lasthop.io/api/dcim/devices/"
http_headers = {}
http_headers["accept"] = "application/json; version=2.4;"
http_headers["Authorization"] = f"Token {token}"

response = requests.get(url, headers=http_headers, verify=False)

for device in response.json()['results']:
    print()
    print("-" * 60)
    print(device['display_name'])
    print("-" * 10)
    print(f"Location: {device['site']['name']}")
    print(f"Vendor: {device['device_type']['manufacturer']['name']}")
    print(f"Status: {device['status']['label']}")
    print("-" * 60)
    print()

# In [3]: response.json()['results']
# Out[3]: 
# [{'id': 3,
#   'name': 'arista1',
#   'display_name': 'arista1',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': {'id': 7,
#    'url': 'http://netbox.lasthop.io/api/dcim/platforms/7/',
#    'name': 'Arista EOS',
#    'slug': 'arista-eos'},
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': {'value': 0, 'label': 'Front'},
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': {'id': 5,
#    'url': 'http://netbox.lasthop.io/api/ipam/ip-addresses/5/',
#    'family': 4,
#    'address': '184.105.247.72/26'},
#   'primary_ip4': {'id': 5,
#    'url': 'http://netbox.lasthop.io/api/ipam/ip-addresses/5/',
#    'family': 4,
#    'address': '184.105.247.72/26'},
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': ['some_group', 'another_group'],
#   'custom_fields': {},
#   'created': '2018-10-26',
#   'last_updated': '2021-12-06T19:24:59.755122-08:00',
#   'local_context_data': None},
#  {'id': 4,
#   'name': 'arista2',
#   'display_name': 'arista2',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': None,
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': None,
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': None,
#   'primary_ip4': None,
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-10-30',
#   'last_updated': '2018-10-30T12:48:27.699741-07:00',
#   'local_context_data': None},
#  {'id': 5,
#   'name': 'arista3',
#   'display_name': 'arista3',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': None,
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': None,
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': None,
#   'primary_ip4': None,
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-10-30',
#   'last_updated': '2018-10-30T14:37:56.312030-07:00',
#   'local_context_data': None},
#  {'id': 6,
#   'name': 'arista4',
#   'display_name': 'arista4',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': None,
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': None,
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': None,
#   'primary_ip4': None,
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-11-01',
#   'last_updated': '2018-11-01T12:12:23.153134-07:00',
#   'local_context_data': None},
#  {'id': 7,
#   'name': 'arista5',
#   'display_name': 'arista5',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': None,
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': None,
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': None,
#   'primary_ip4': None,
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-11-01',
#   'last_updated': '2018-11-01T12:28:21.631754-07:00',
#   'local_context_data': None},
#  {'id': 8,
#   'name': 'arista6',
#   'display_name': 'arista6',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': {'id': 7,
#    'url': 'http://netbox.lasthop.io/api/dcim/platforms/7/',
#    'name': 'Arista EOS',
#    'slug': 'arista-eos'},
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/2/',
#    'name': 'RK2',
#    'display_name': 'RK2'},
#   'position': None,
#   'face': None,
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': None,
#   'primary_ip4': None,
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-11-01',
#   'last_updated': '2021-12-10T06:34:41.683525-08:00',
#   'local_context_data': None},
#  {'id': 9,
#   'name': 'arista7',
#   'display_name': 'arista7',
#   'device_type': {'id': 2,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/2/',
#    'manufacturer': {'id': 6,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/6/',
#     'name': 'Arista',
#     'slug': 'arista'},
#    'model': 'vEOS',
#    'slug': 'veos'},
#   'device_role': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/3/',
#    'name': 'Distribution Switch',
#    'slug': 'distribution-switch'},
#   'tenant': None,
#   'platform': None,
#   'serial': '',
#   'asset_tag': None,
#   'site': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/3/',
#    'name': 'AWS US West1',
#    'slug': 'aws-us-west1'},
#   'rack': None,
#   'position': None,
#   'face': None,
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': None,
#   'primary_ip4': None,
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-11-02',
#   'last_updated': '2021-11-19T12:58:30.642168-08:00',
#   'local_context_data': None},
#  {'id': 1,
#   'name': 'cisco1',
#   'display_name': 'cisco1',
#   'device_type': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/1/',
#    'manufacturer': {'id': 2,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/2/',
#     'name': 'Cisco',
#     'slug': 'cisco'},
#    'model': '881',
#    'slug': 'cisco881'},
#   'device_role': {'id': 7,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/7/',
#    'name': 'Router',
#    'slug': 'router'},
#   'tenant': None,
#   'platform': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/platforms/1/',
#    'name': 'Cisco IOS',
#    'slug': 'cisco-ios'},
#   'serial': 'FTX1512038X',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': {'value': 0, 'label': 'Front'},
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/ipam/ip-addresses/3/',
#    'family': 4,
#    'address': '184.105.247.70/26'},
#   'primary_ip4': {'id': 3,
#    'url': 'http://netbox.lasthop.io/api/ipam/ip-addresses/3/',
#    'family': 4,
#    'address': '184.105.247.70/26'},
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-10-25',
#   'last_updated': '2018-10-26T15:09:15.249257-07:00',
#   'local_context_data': None},
#  {'id': 2,
#   'name': 'cisco2',
#   'display_name': 'cisco2',
#   'device_type': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-types/1/',
#    'manufacturer': {'id': 2,
#     'url': 'http://netbox.lasthop.io/api/dcim/manufacturers/2/',
#     'name': 'Cisco',
#     'slug': 'cisco'},
#    'model': '881',
#    'slug': 'cisco881'},
#   'device_role': {'id': 7,
#    'url': 'http://netbox.lasthop.io/api/dcim/device-roles/7/',
#    'name': 'Router',
#    'slug': 'router'},
#   'tenant': None,
#   'platform': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/platforms/1/',
#    'name': 'Cisco IOS',
#    'slug': 'cisco-ios'},
#   'serial': 'FTX18298312',
#   'asset_tag': None,
#   'site': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/sites/1/',
#    'name': 'Fremont Data Center',
#    'slug': 'fremont-dc'},
#   'rack': {'id': 1,
#    'url': 'http://netbox.lasthop.io/api/dcim/racks/1/',
#    'name': 'RK1',
#    'display_name': 'RK1'},
#   'position': None,
#   'face': {'value': 0, 'label': 'Front'},
#   'parent_device': None,
#   'status': {'value': 1, 'label': 'Active'},
#   'primary_ip': {'id': 4,
#    'url': 'http://netbox.lasthop.io/api/ipam/ip-addresses/4/',
#    'family': 4,
#    'address': '184.105.247.71/26'},
#   'primary_ip4': {'id': 4,
#    'url': 'http://netbox.lasthop.io/api/ipam/ip-addresses/4/',
#    'family': 4,
#    'address': '184.105.247.71/26'},
#   'primary_ip6': None,
#   'cluster': None,
#   'virtual_chassis': None,
#   'vc_position': None,
#   'vc_priority': None,
#   'comments': '',
#   'tags': [],
#   'custom_fields': {},
#   'created': '2018-10-26',
#   'last_updated': '2018-10-26T15:25:01.152779-07:00',
#   'local_context_data': None}]
# 
